# -*- coding: utf-8 -*-
"""Prac8(vizual).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z1u7F-xGDmS1SVg_U6DFHJTNJ50ySum2

<a href="https://colab.research.google.com/github/PankajAgarwalS/TE-COMP-SEM-6/blob/main/Prac8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Titanic Vizualization**
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
df=sns.load_dataset('titanic')

df.head()

df.info()

"""## **Line Plot**"""

sns.lineplot(x=df['age'].value_counts(), y='age', data=df)

"""## **Bar Plot**"""

sns.countplot(x ='class', data = df)

sns.countplot(x ='sex', data = df)

sns.countplot(x ='alone', data = df)

"""## **Histogram**"""

sns.histplot( x='age', data=df)

sns.histplot( x='fare', data=df)

sns.histplot( x='fare', data=df , bins=50, kde=True)

"""## **Pie Chart**"""

df['sex'].value_counts().plot(kind="pie", autopct="%.2f")

df['alive'].value_counts().plot(kind="pie", autopct="%.2f")

df['class'].value_counts().plot(kind="pie", autopct="%.2f")

df['alone'].value_counts().plot(kind="pie", autopct="%.2f")

"""## **Scatter Plot**"""

sns.scatterplot(x='fare', y='age', data=df)

sns.scatterplot(x='fare', y='age', hue='sex',data=df)

"""## **Box Plot**"""

sns.boxplot( y='fare', data=df)

sns.boxplot( y='age', data=df)

df_numeric = df.select_dtypes(include=['number'])
corr_matrix = df_numeric.corr()
sns.heatmap(corr_matrix, annot=True)