# -*- coding: utf-8 -*-
"""Prac10(vizuali).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yVs9bvfyGE6IeS-sNu1rzgNcKVjOWmSf

<a href="https://colab.research.google.com/github/PankajAgarwalS/TE-COMP-SEM-6/blob/main/Prac10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
"""

import pandas as pd
import seaborn as sns

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

column_names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']
df = pd.read_csv(url, names=column_names)

df.head()

df.describe()

print("Features and their types:")
df.dtypes

df.info()

df.plot(kind='box',figsize=(10,8))

df.hist(figsize=(10,8))

sns.boxplot(data=df.drop(columns='class'), orient="h")

def identify_outliers(feature):
    q1 = feature.quantile(0.25)
    q3 = feature.quantile(0.75)
    iqr = q3 - q1
    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr
    outliers = feature[(feature < lower_bound) | (feature > upper_bound)]
    return outliers

outliers_dict = {}
for feature in df.columns[:-1]:
    outliers_dict[feature] = identify_outliers(df[feature])

for feature, outliers in outliers_dict.items():
    print(f'Outliers for {feature}:')
    print(outliers)