# -*- coding: utf-8 -*-
"""Prac3.1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FXUmnwfv_Zb0eqgcOyWlMDWX48UZyi8o
"""

import pandas as pd
import numpy as np
import seaborn as sns
from seaborn.utils import get_dataset_names
df=sns.load_dataset('tips')

"""### General Information of Dataset"""

print("Shape of the DataFrame:")
print(df.shape)

df.sample(5)

df.info()

df.describe()

df.isnull().sum()

"""### Descriptive Statistics"""

mean = df['total_bill'].mean()
print("total bill Mean:", mean)

mean = df['tip'].mean()
print("tip Mean:", mean)

mean = df['size'].mean()
print("size Mean:",mean)

mode_sex = df['sex'].mode().values[0]
print("Mode of 'sex' column:", mode_sex)

mode_smoker = df['smoker'].mode().values[0]
print("Mode of 'smoker' column:", mode_smoker)

mode_day = df['day'].mode().values[0]
print("Mode of 'day' column:", mode_day)

mode_time = df['time'].mode().values[0]
print("Mode of 'time' column:", mode_time)

mode_tip = df['tip'].mode().values[0]
print("Mode of 'tip' column:", mode_tip)

median = df['total_bill'].median()
print("total bill Mean:", median)

median = df['tip'].median()
print("tip Mean:", median)

median = df['size'].median()
print("size Mean:",median)

variance_total_bill = df['total_bill'].var()
print("Variance total_bill:", variance_total_bill)

variance_tip = df['tip'].var()
print("Variance tip:", variance_tip)

std_dev_total_bill = df['total_bill'].std()
print("Standard Deviation of total_bill:", std_dev_total_bill)

std_dev_tip = df['tip'].std()
print("Standard Deviation of tip:", std_dev_tip)

covariance = df['total_bill'].cov(df['tip'])
print("Covariance:", covariance)

correlation = df['total_bill'].corr(df['tip'])
print("Correlation:", correlation)

"""### Descriptive Statistics by Group"""

grouped_df=df.groupby('smoker')

mean = grouped_df.mean(numeric_only=True)
print(mean)

median = grouped_df.median(numeric_only=True)
print(median)

min_val = grouped_df.min(numeric_only=True)
print(min_val)

max_val = grouped_df.max(numeric_only=True)
print(max_val)

std = grouped_df.std(numeric_only=True)
print(std)

grouped_df=df.groupby('day')

mean = grouped_df.mean(numeric_only=True)
print(mean)

median = grouped_df.median(numeric_only=True)
print(median)

min_val = grouped_df.min(numeric_only=True)
print(min_val)

max_val = grouped_df.max(numeric_only=True)
print(max_val)

std = grouped_df.std(numeric_only=True)
print(std)

grouped_df = df.groupby('time')

mean = grouped_df.mean(numeric_only=True)
print(mean)

median = grouped_df.median(numeric_only=True)
print(median)

min_val = grouped_df.min(numeric_only=True)
print(min_val)

max_val = grouped_df.max(numeric_only=True)
print(max_val)

std = grouped_df.std(numeric_only=True)
print(std)