# -*- coding: utf-8 -*-
"""Prac3.2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19ov1jH842SNtGmzt7EZJBG31uRj1OZ2V
"""

import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

iris = load_iris()
iris.keys()

df = pd.DataFrame(iris.data)
df.describe()

df = pd.DataFrame(iris.data, columns = iris.feature_names)
df["label"] = iris.target
iris.target_names

df.shape

df.info()

df.describe()

"""### Setosa, Versicolor and Virginica"""

setosa =df[df["label"] == 0].drop("label", axis=1)
setosa.describe()

versicolor = df[df["label"] == 1].drop("label", axis=1)
versicolor.describe()

virginica = df[df["label"] == 2].drop("label", axis=1)
virginica.describe()