# -*- coding: utf-8 -*-
"""Prac2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11OVPB-fw4ZvorPpP39wLgyckBKJmd9pD
"""

import pandas as pd
import numpy as np
import seaborn as sns
df = pd.read_csv('academic.csv')
df

df.info()

df.sample(5)

df.shape

df.describe()

sns.boxplot(data=df, orient="h")

df.isnull().sum()

df['raisedhands']=df['raisedhands'].fillna(df['raisedhands'].mean)
df.isnull().sum()

df['Discussion']=df['Discussion'].fillna(df['Discussion'].mean)
df.isnull().sum()

df['VisITedResources']=df['VisITedResources'].fillna(method='ffill')
df.isnull().sum()

df['AnnouncementsView']=df['AnnouncementsView'].fillna(method='ffill')
df.isnull().sum()

df['ParentAnsweringSurvey']=df['ParentAnsweringSurvey'].astype(bool)
df.sample(5)

df['Discussion'] = pd.to_numeric(df['Discussion'], errors='coerce')
print("Skewness before transformation:", df['Discussion'].skew())
df['Discussion_sqrt'] = np.sqrt(df['Discussion'])

print("Skewness after transformation:", df['Discussion_sqrt'].skew())

df['raisedhands'] = pd.to_numeric(df['raisedhands'], errors='coerce')

print("Skewness before transformation:")
print(df['raisedhands'].skew())

df['raisedhands_sqrt'] = np.sqrt(df['raisedhands'])

print("Skewness after transformation:")
print(df['raisedhands_sqrt'].skew())

df['AnnouncementsView'] = pd.to_numeric(df['AnnouncementsView'], errors='coerce')

print("Skewness before transformation:")
print(df['AnnouncementsView'].skew())

df['AnnouncementsView_sqrt'] = np.sqrt(df['AnnouncementsView'])

print("Skewness after transformation:")
print(df['AnnouncementsView_sqrt'].skew())