# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13fV15-_ymEkxQcOATfm9ao-CVN6oEoYo
"""

import pandas as pd
import numpy as np
import seaborn as sns
titanic = sns.load_dataset('titanic')

titanic.head(5)

titanic.sample(5)

titanic.info()

print("\nData Dimensions:\n")
titanic.shape

print("\nData Description:\n")
titanic.describe()

print("\nVariable Descriptions:\n")
titanic.dtypes

"""### **Removing Null values**"""

print("Data Preprocessing - Missing Values:\n")
titanic.isnull()

print("Data Preprocessing -  Sum of Missing Values:\n")
titanic.isnull().sum()

titanic['age'] = titanic['age'].fillna(titanic['age'].mean())

print("Data Preprocessing -  Sum of Missing Values after removing null values of age:\n")
titanic.isnull().sum()

titanic=titanic.drop(columns=['deck'])
titanic.isnull().sum()

titanic['embarked']=titanic['embarked'].fillna(method='ffill')
titanic.isnull().sum()

titanic['embark_town']=titanic['embark_town'].fillna(method='bfill')
titanic.isnull().sum()

titanic=titanic.dropna()
titanic.isnull().sum()

"""### **Variable types**"""

titanic.dtypes

titanic['alive']=titanic['alive'].astype(bool)
titanic.sample(5)

titanic['adult_male']=titanic['adult_male'].astype(int)
titanic.sample(5)