# -*- coding: utf-8 -*-
"""Prac9(vizual).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15UfEPgUtWRDQ3LN1MgTGcle86FwYEH8O

<a href="https://colab.research.google.com/github/PankajAgarwalS/TE-COMP-SEM-6/blob/main/Prac9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Titanic Vizualization**
"""

import seaborn as sns
import matplotlib.pyplot as plt
df=sns.load_dataset('titanic')

df.head()

df.info()

"""## **Box Plot**"""

sns.boxplot( y='age', data=df)

sns.boxplot( x='sex',y='age', data=df)

sns.boxplot( x='survived',y='age', data=df)

sns.boxplot( x='sex',y='age',hue='survived', data=df)